### ISSUE TITLE
Need support for disconnecting user after logout

### ISSUE THREAD

**Issue by SohailAsghar236** [wifidog/wifidog-auth-laravel#112]
@sinkcup Are you still providing support for this repo or abandoned it? Please at least update.

**Comment by sinkcup** [comment]
yes, I am here

**Comment by sinkcup** [comment]
I have check the code, after you click logout from the auth server web, you will be redirected to gateway's logout page, is it OK?

https://github.com/wifidog/wifidog-auth-laravel/blob/756b5fd0071008b759c68d737ddbd0bf0a196981/app/Http/Controllers/Auth/LoginController.php#L77

**Comment by SohailAsghar236** [comment]
@sinkcup Thank you for your response. Yes, I got error. The logout didn't complete. I was stuck on IP:2060 page. The user is never disconnected after logging out. Internet connection stays alive.

**Comment by SohailAsghar236** [comment]
I would also like to know how to apply timeout, upload and download rate to a user?

**Comment by sinkcup** [comment]
what is the error?

debug wifidog: edit /usr/bin/wifidog-init, change "start" section's "wifidog $OPTIONS" to "wifidog -f -d 9"

**Comment by SohailAsghar236** [comment]
I am using WiFiDog Auth Laravel as authentication server with Ruijie AP. The AP is acting as gateway. I have not setup a gateway server. The authentication process is working (token verification and internet access after authentication) but I don't get portal page loaded to show that internet is connected and if I manually try to logout from auth server, I get error.

![image_1731505523436_dthig1731505523439](https://github.com/user-attachments/assets/1316fdc4-50a3-46bf-b186-672ed5a46ce2)
![image_1731505538625_b43no1731505538627](https://github.com/user-attachments/assets/47d14d4b-de0f-474e-b3dd-a1a88cf04055)

**Comment by sinkcup** [comment]
the second image means you can not connect to Ruijie AP port 2060, try 80

https://www.ruijienetworks.com/support/documents/slide_rg-wlan-series-access-points-web-based-configuration-guide-en/?page=html&keyworks=wifidog

**Comment by SohailAsghar236** [comment]
I have tried the **80 port** and it didn't work either. This is the URL sent to auth server from AP when I connect to the WiFi SSID for which authentication is enable:

**https://wifidog.appcraftr.com/login/?gw_id=G1QPBCJ099868&gw_sn=G1QPBCJ099868&gw_address=192.168.23.1&gw_port=2060&ip=192.168.23.2&mac=7c:5c:f8:ca:2e:25&apmac=9c2b.a6a2.e075&ssid=.%40%40WiFidog&url=http%3A%2F%2Fwww.msftconnecttest.com%2Fredirect&vlanid=233**

The login page loads and I am able to login with valid credentials and token is generated:

**http://192.168.23.1:2060/wifidog/auth?token=17a8a0a86a4beee7f8be959e1959fd9d**

Internet access is opened but I can't see the portal page or any status page. I manually tried to logout and even that is not working.

**Comment by SohailAsghar236** [comment]
@sinkcup When I run this command for Ruijie AP (RG AP-820-L (V2)):

**show web-auth rdport**

I get this response:
**Rd-Port:
80 443**

**Comment by sinkcup** [comment]
1. screenshot of browser open `http://192.168.23.1:2060/wifidog/auth?token=xxx`

2. command run:

```
curl -I http://192.168.23.1:2060/wifidog/auth?logout=1&token=xxx
```

**Comment by SohailAsghar236** [comment]
@sinkcup 

Take a look please:

![image](https://github.com/user-attachments/assets/ed73a921-3aa5-4536-8160-a6f294f04f60)


![image](https://github.com/user-attachments/assets/bc3bdca7-8ccd-41db-bc23-7807b78d37c9)

**Comment by SohailAsghar236** [comment]
> 1. screenshot of browser open `http://192.168.23.1:2060/wifidog/auth?token=xxx`

![image](https://github.com/user-attachments/assets/0a8fb2a7-8065-4828-8ac2-eebc630fc5af)

> 2. command run:

curl -I http://192.168.23.1:2060/wifidog/auth?logout=1&token=xxx

Response:
**Error: Failure when receiving data from the peer**

**Comment by sinkcup** [comment]
`Redirection HTTP Port: 80` is fine, it will redirect to login page when user access internet by http 80.

443 is optional, 2060 is wrong.

**Comment by sinkcup** [comment]
browser open `http://192.168.23.1:2060/wifidog/auth?token=xxx`

but your screenshot is `http://192.168.23.1/wifidog/auth?token=xxx`

**Comment by SohailAsghar236** [comment]
> `Redirection HTTP Port: 80` is fine, it will redirect to login page when user access internet by http 80.
> 
> 443 is optional, 2060 is wrong.

I removed 2060. Just added for checking if WiFiDog is using it.

**Comment by SohailAsghar236** [comment]
> browser open `http://192.168.23.1:2060/wifidog/auth?token=xxx`
> 
> but your screenshot is `http://192.168.23.1/wifidog/auth?token=xxx`

@sinkcup Apologies for the mistake. Here is the correct screenshot:

![image](https://github.com/user-attachments/assets/8573ac67-dec0-48ec-ba54-e5fae24bc513)

**Comment by sinkcup** [comment]
is your config right?

<img width="513" alt="image" src="https://github.com/user-attachments/assets/d56e7705-4dab-443b-8144-456c923964cc">

**Comment by SohailAsghar236** [comment]
@sinkcup Please check:

![image](https://github.com/user-attachments/assets/99ac46f1-d2c3-4d6c-981f-6d6a2338df22)

Telnet command output:

web-auth template wifidog1 wifidog
 ip 106.0.62.78
 nas-ip 192.168.23.1
 url https://wifidog.appcraftr.com/
 redirect js
!

**Comment by sinkcup** [comment]
1. change url https://wifidog.appcraftr.com/login
2. Ruijie AP wifidog port 2060 reset is not a good news, contact Ruijie for wifidog debug log, or virtual a Linux as router, or use a cheap OpenWrt router to test.

**Comment by sinkcup** [comment]
in the wifidog protocol v1, there is no NAS, I don't known what is it, maybe it cause error?

https://github.com/wifidog/wifidog-auth-laravel/wiki/WiFiDog-Protocol-V1

**Comment by SohailAsghar236** [comment]
@sinkcup Thank you for the feedback. Let me check and get back to you.

Is the timeout, upload and download rate work is not done in auth server? What should I do if I want to allow a user just 10 minutes of internet?

**Comment by SohailAsghar236** [comment]
@sinkcup I modified the **LoginController** to change code for token. The authentication wasn't working before. It worked after I made the token 32 bit.

![image](https://github.com/user-attachments/assets/45c43e65-7b15-41f4-a7fa-8c4fa59eae8e)

**Comment by SohailAsghar236** [comment]
@sinkcup Please respond on timeout point. I need help with that.

**Comment by SohailAsghar236** [comment]
@sinkcup Yes, the token is too long and is being rejected by gateway. I borrowed the hash code from original WiFiDog auth code that is written in core PHP.

Please responsd how to add a timeout, upload and download rate parameters?

**Comment by SohailAsghar236** [comment]
@sinkcup Please response to timeout, upload and download rate parameters and if this is implemented? Do I need to create a new issue for this?

**Comment by sinkcup** [comment]
yes, you should create a new issue for it.

it's a new feature, now it does not exist.
