### ISSUE TITLE
build: upgrade to Laravel 11

### ISSUE THREAD

**Issue by sinkcup** [wifidog/wifidog-auth-laravel#113]
```
Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /Users/sink/development/wifidog-auth-laravel/config/logging.php on line 40

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/sink/development/wifidog-auth-laravel/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1277
```

**Comment by sinkcup** [comment]
upgrade PHP version is not enough, should upgrade to Laravel 11

**Comment by SohailAsghar236** [comment]
@sinkcup Please push or merge the new Laravel 11 changes once done with testing. Please add TailwindCSS instead of Bootstrap 5 if possbile.

**Comment by sinkcup** [comment]
wifidog api middleware should be changed to AuthenticationException

https://stackoverflow.com/a/78829592/3606894

**Comment by sinkcup** [comment]
wifidog token in query string, should change laravel Sanctum::getAccessTokenFromRequestUsing

https://stackoverflow.com/a/74006702/3606894

**Comment by sinkcup** [comment]
api_token be changed to laravel Sanctum

https://laravel.com/docs/11.x/sanctum

**Comment by sinkcup** [comment]
register done.

<img width="567" alt="image" src="https://github.com/user-attachments/assets/523797f2-72c9-4a91-87ce-a23b6a75dc54">

**Comment by sinkcup** [comment]
laravel 11 use frankenphp not apache

https://laravel.com/docs/11.x/deployment

**Comment by sinkcup** [comment]
frankenphp need too many prepare, back to apache

<img width="515" alt="image" src="https://github.com/user-attachments/assets/e17980b0-d987-4c22-88c1-17098530a406">
