### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by Cm-8** [wifidog/wifidog-auth-laravel#13]
Is wifidog still maintained or is it abandoned? The last commit of wifidog-gateway is 1 year ago.
It work with openwrt 18?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sinkcup** [comment]
you could try to compile it on openwrt 18 sdk.
if error, you should create issue at https://github.com/wifidog/wifidog-gateway/issues
