### ISSUE TITLE
Internet access issue after Laravel 11 Upgrade

### ISSUE THREAD

**Issue by SohailAsghar236** [wifidog/wifidog-auth-laravel#146]
@sinkcup 

The WiFiDog gateway (**for me it's the Ruijie AP**) is not allowing internet access since I upgraded to Laravel 11.

With the last code (**Laravel 6**) after token issue was fixed, it was working but it's not working now.

**Comment by sinkcup** [comment]
token format is changed. you should login from web again, you will find the new token.

**Comment by SohailAsghar236** [comment]
@sinkcup

I have the latest code. I cloned the repo from scratch.

**Comment by SohailAsghar236** [comment]
> token format is changed. you should login from web again, you will find the new token.

@sinkcup I have tried to login from web multiple times. The current token is around 50 characters.

**Comment by sinkcup** [comment]
Laravel Sanctum is the simplest authentication for Laravel 11.

There shouldn't be a simpler way to authenticate.

**Comment by sinkcup** [comment]
50 characters is not long, it should work fine.

what's your error?

**Comment by SohailAsghar236** [comment]
@sinkcup 

![image](https://github.com/user-attachments/assets/4f76e6b8-faa6-4c10-8158-d94567b49c09)

Please check.

There isn't any error. AP isn't allowing internet after authentication. It was working fine before.

**Comment by SohailAsghar236** [comment]
@sinkcup 

This was the error after login:

![image](https://github.com/user-attachments/assets/a65b859e-1325-4309-8e54-65d6576d5934)

I fixed it by adding /portal route and PortalController from previous code.

![image](https://github.com/user-attachments/assets/3009c48d-f9d4-433a-82e6-166c33e02cee)

Now the issue is that there is **no error** but still internet is not allowed by gateway.

**Comment by sinkcup** [comment]
what's the url of "start internet", what happen if you click it?

**Comment by SohailAsghar236** [comment]
> what's the url of "start internet", what happen if you click it?

**This is the URL for start internet:**

http://192.168.23.1:2060/wifidog/auth?token=token_here

**What happens when I click it:**

The above mentioned URL is called and I am taken to portal page which takes me back to dashboard page, in short, same page reloads and nothing happens (**internet not allowed by gateway**).

**Comment by sinkcup** [comment]
it seems I forgot PortalController, I will copy it back.

but it seems have no relevance with your problem.

**Comment by SohailAsghar236** [comment]
> but it seems have no relevance with your problem.

True but internet is not allowing now. It was working with the previous code.

**Comment by sinkcup** [comment]
are you OK?

**Comment by SohailAsghar236** [comment]
@sinkcup 

I am testing the connectivity after adding new changes that you merged. Please hold off closing this issue as it is not fixed yet.

**Comment by SohailAsghar236** [comment]
@sinkcup 

Internet is still not opening even after login and authentication.

![image](https://github.com/user-attachments/assets/079af152-e296-4d52-b727-f187208222b6)

**Comment by sinkcup** [comment]
the problem should occur after browser request `http://192.168.23.1:2060/wifidog/auth?token=foo`

then the gateway request:

```
http://auth_server:port/auth?ip=$ip&mac=$mac&token=$token&stage=login
```

you try this:

```
curl "http://auth_server:port/auth?ip=$ip&mac=$mac&token=$token&stage=login"
```

check the response

**Comment by sinkcup** [comment]
could you get the wifidog log?

if you can ssh into the router, edit `/usr/bin/wifidog-init`, change "start" section's "wifidog $OPTIONS" to "wifidog -f -d 9"

It is recommended to use an openwrt device that can ssh for wifidog development.

**Comment by SohailAsghar236** [comment]
@sinkcup 

I tried the **cURL** command and here is the response:

For **https://wifidog.appcraftr.com/auth?ip=192.168.23.2&mac=7c:5c:f8:ca:2e:25&token=9|1SVmlhMEbSfMHNYiYIt0dGZrCkF5bXEZKaoLtcVt73ef6976&stage=login**

**Reponse:**
Auth: -1

**Status code:**
400 Bad Request

I think the issue is with the token generated. I don't know what is **9|1** in the beginning of the token and I tried to use the previous method to generate a token and here is the reponse with that token:

For **https://wifidog.appcraftr.com/auth?ip=192.168.23.2&mac=7c:5c:f8:ca:2e:25&token=4e4c3152b064b84bf63dd377563078a4&stage=login**

**Reponse:**
Auth: 0

**Status code:**
401 Unauthorized

Also when I ran **cURL** command, the token:

**9|1SVmlhMEbSfMHNYiYIt0dGZrCkF5bXEZKaoLtcVt73ef6976**

printed as:

**9%7C1SVmlhMEbSfMHNYiYIt0dGZrCkF5bXEZKaoLtcVt73ef6976**

**Comment by SohailAsghar236** [comment]
> could you get the wifidog log?
> 
> if you can ssh into the router, edit `/usr/bin/wifidog-init`, change "start" section's "wifidog $OPTIONS" to "wifidog -f -d 9"
> 
> It is recommended to use an openwrt device that can ssh for wifidog development.

@sinkcup 

For some reasons, I am not using the openWRT router and I have to stick with Ruijie AP router and I can try to ssh into router and see if Ruijie OS allows to edit wifidog-init which is highly unlikely.

To make things clear, I want you to know that I am not running a separate WiFiDog Gateway and AP is acting as WiFiDog Gateway. I am in the process of creating a VM to act as a DHCP server and Gateway for the AP but I am missing a guide for it and don't know the complete steps to implement it.

Can you guide me to setup a VM that acts as WiFiDog Gateway and handles DHCP or point me in the right direction?

I will be thankful.

**Comment by SohailAsghar236** [comment]
@sinkcup Do you need more information on this?

**Comment by sinkcup** [comment]
I find the reason:

code require `gw_id`, it's wrong.

the docs say not need `gw_id`.

https://github.com/wifidog/wifidog-auth-laravel/blob/4efab8a912bd464ee3e50465017d1e93afb4e05a/app/Http/Controllers/API/AuthController.php#L35

https://github.com/wifidog/wifidog-auth-laravel/wiki#auth-server-authentication-protocol

**Comment by sinkcup** [comment]
I'm fine, are you OK?

<img width="968" alt="image" src="https://github.com/user-attachments/assets/61839258-daee-4d98-bb54-76dd1976b998">

**Comment by SohailAsghar236** [comment]
@sinkcup I am getting same response for cURL as you.

I am getting **200 OK** but still, internet access is not opening by AP.

I still can't figure out the issue. I think the issue might be with **.env** file where **SESSION_DRIVE=database**.

**Comment by SohailAsghar236** [comment]
@sinkcup 

**gw_id** was required in **Laravel 6** code but it was working after token error fix.

**Comment by SohailAsghar236** [comment]
@sinkcup 

I tried to log the AuthController method to see if a request is made to it after user login, but the log file was never filled. Log was never generated for the AuthController API method. When I ran the cURL command for /auth, log was generated but it didn't work when I logged in user via login page and clicked start internet button. I think request is never made to /auth API route even after login.

![SAD](https://github.com/user-attachments/assets/a486871c-f0b7-4c62-80c6-6e156a32c9fc)

Please check this screenshot. After I login, portal is called three times and login is again called three times before showing me the dashboard.

**Comment by sinkcup** [comment]
I can't debug without wifidog log.
Call me when you can ssh into the router and get the log.
