### ISSUE TITLE
Would this Mikrotik RB951Ui-2HnD work?

### ISSUE THREAD

**Issue by LaravDev** [wifidog/wifidog-auth-laravel#22]
I have checked the list of supported routers for OpenWrt, do you think this router will work well for this purpose? Mikrotik RB951Ui-2HnD

The idea is to make the facebook login in order to get data for marketing... is there any step by step tutorial to use this package?

Thanks in advance...

**Comment by LaravDev** [comment]
Or it could be an Asus RT-AC58U maybe?

**Comment by sinkcup** [comment]
you should seach at https://openwrt.org/toh/start

both Mikrotik RB951Ui-2HnD and Asus RT-AC58U are ready for openwrt.

1. you need to flash the route to openwrt. if you don't skilled at it, you should by a OBBE open source router, e.g. Linksys ACS series

https://openwrt.org/supported_devices

https://openwrt.org/toh/hwdata/asus/asus_rt-ac58u

https://openwrt.org/toh/hwdata/mikrotik/mikrotik_rb951ui-2hnd

2. compile wifidog ipk, copy into the router and install it

**Comment by LaravDev** [comment]
> you should seach at https://openwrt.org/toh/start
> 
> 
> 
> both Mikrotik RB951Ui-2HnD and Asus RT-AC58U are ready for openwrt.
> 
> 
> 
> 1. you need to flash the route to openwrt. if you don't skilled at it, you should buy a OBBE open source router, e.g. Linksys ACS series
> 
> 
> 
> https://openwrt.org/toh/hwdata/asus/asus_rt-ac58u
> 
> 
> 
> https://openwrt.org/toh/hwdata/mikrotik/mikrotik_rb951ui-2hnd
> 
> 
> 
> 2. compile wifidog ipk, copy into the router and install it
> 
> 

Thanks! I'll start there!
