### ISSUE TITLE
Docker on EC2 AWS

### ISSUE THREAD

**Issue by spray12345** [wifidog/wifidog-auth-laravel#23]
https://my.pcloud.com/publink/show?code=XZ1lHN7ZMMyumpVQdIXYUl4MYbDzzVt0LmL7

Unable to find image 'wifidog/wifidog-auth-laravel-forked:master' locally
docker: Error response from daemon: pull access denied for wifidog/wifidog-auth-laravel-forked, repository does not exist or may require 'docker login'.
See 'docker run --help'.

im so close getting the AUTH server up and running ...

please SInkCup, 

what am i doing wrong ?

**Comment by sinkcup** [comment]
I am so sorry, I had given you the wrong name of the docker hub image, the correct command is:

```
docker run --rm -t "wifidog/wifidog-auth-laravel"
```

https://cloud.docker.com/u/wifidog/repository/docker/wifidog/wifidog-auth-laravel

**Comment by Spray1983** [comment]
hi SinkCup,

https://cloud.docker.com/u/wifidog/repository/docker/wifidog/wifidog-auth-laravel

https://my.pcloud.com/publink/show?code=XZglzN7ZzRLmRl9A2qf0R4W6JsK4m8cb2CRX

http 404 error code?

**Comment by Spray1983** [comment]
https://my.pcloud.com/publink/show?code=XZHdzN7Z0gniLAMi50JeH6LlDlhblLbGiTt7

**Comment by sinkcup** [comment]
sorry, here is the public link:

https://hub.docker.com/r/wifidog/wifidog-auth-laravel

**Comment by sinkcup** [comment]
SQL connection error...

you should change the address to your MySQL server on AWS.

**Comment by Spray1983** [comment]
Aaaaaaaaaaaaaaaaaaaa very nice

This then also means ….

Ip, address
User
And pass

Very good I try right a way sir 😊



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Spray1983** [comment]
https://my.pcloud.com/publink/show?code=XZDEzN7ZApklbu1CCQyWnJYiUTuhzVgd5lk7


moving closer, 

yet it builds and starts up, and then it closes gracefully ?

**Comment by sinkcup** [comment]
run with one more env:

```
JWT_SECRET=EYyXkh0xqc9mdDB93KQVfit0ykyTAknuNlmoPnGkp0cfiFScFMBSy6Prlk0DZdg8
```

and if you change the window size, docker will be shut down gracefully

**Comment by Spray1983** [comment]
https://my.pcloud.com/publink/show?code=XZqOzN7ZCGd7OMkkjzRcjAyepqHdi72M2LkX

how can i figure out, what the correct dns name is to reach the auth server ?

**Comment by sinkcup** [comment]
follow the AWS docs: https://aws.amazon.com/getting-started/tutorials/deploy-docker-containers/

**Comment by Spray1983** [comment]
![dockah](https://user-images.githubusercontent.com/30536353/59158916-01ccd380-8ac2-11e9-8518-159cb5cd7bf6.JPG)
