### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by rainbowhat** [wifidog/wifidog-auth-laravel#3]
Hi ,

Is Facebook login possible ?

**Comment by sinkcup** [comment]
yes, it's usefull, I will add this feature.

**Comment by sinkcup** [comment]
done, but have no test...
![screenshot_2018-01-28-22-34-03-722_quark browser](https://user-images.githubusercontent.com/4971414/35483355-d5079ae2-047b-11e8-8e5a-eb79bf4ca205.png)

**Comment by rainbowhat** [comment]
@sinkcup nice! I'm left with trying to change my Unifi AC AP firmware which I cant, looking for alternative AP AC now :(

**Comment by sinkcup** [comment]
@rainbowhat OBBE openwrt router is the best choice for developers.
https://openwrt.io/docs/supported-devices/#oobe-openwrt

suggest:

Linksys WRT1900ACS $199
https://www.linksys.com/us/p/P-WRT1900ACS/

Hiwifi GEE j3pro $49 (only sale in China) @rssnsj
http://www.hiwifi.com/j3pro-view
https://wiki.openwrt.org/toh/hiwifi/gee/hiwifi_gee_hc5661

**Comment by rainbowhat** [comment]
@sinkcup  Thanks , looking into it now, I need an AP , already got a router haha. 

Unifi AC AP LR is really shit, their software can't work properly got captive portal. Shit router really
