### ISSUE TITLE
what's the difference with authpuppy ?

### ISSUE THREAD

**Issue by medrockstar** [wifidog/wifidog-auth-laravel#4]
Hi,

I want to build captive portal with external authentification, when user can login to my OpenWrt with  email or facebook.

the app of the captive portal must be in external server.

wifidog-auth-laravel can do that, and what's the diffrence with authpuppy ?

tks,

**Comment by sinkcup** [comment]
authpuppy Latest commit on 18 Jan 2013

wifidog-auth-laravel Latest commit on 2018
