### ISSUE TITLE
artisian migrate error php 7.3

### ISSUE THREAD

**Issue by reinethernal** [wifidog/wifidog-auth-laravel#42]
Illuminate\Database\QueryException  : could not find driver (SQL: PRAGMA foreign_keys = ON;)

  at /home/captive/wifidog-auth-laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("could not find driver")
      /home/captive/wifidog-auth-laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("could not find driver")
      /home/captive/wifidog-auth-laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.

   Whoops\Exception\ErrorException  : PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20180731/mysqli (/usr/lib/php/20180731/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mysqli.so (/usr/lib/php/20180731/mysqli.so: undefined symbol: mysqlnd_global_stats))

  at Unknown:0
    1|

  Exception trace:

  1   Whoops\Run::handleError("PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20180731/mysqli (/usr/lib/php/20180731/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/mysqli.so (/usr/lib/php/20180731/mysqli.so: undefined symbol: mysqlnd_global_stats))", "Unknown")
      /home/captive/wifidog-auth-laravel/vendor/filp/whoops/src/Whoops/Run.php:433

  2   Whoops\Run::handleShutdown()
      [internal]:0

**Comment by sinkcup** [comment]
you need to install mysqli on your server

**Comment by reinethernal** [comment]
Fixed, thx. Found that error was in difference between packets provided at system repo and onrdrej's ppa.
