### ISSUE TITLE
support nginx

### ISSUE THREAD

**Issue by AlexYe233** [wifidog/wifidog-auth-laravel#44]
Hi,is it possible that wifidog-auth-laravel be deployed with nginx？

**Comment by sinkcup** [comment]
of course, you could use Nginx with PHP-FPM.
docs: https://laravel.com/docs/6.x/deployment

**Comment by AlexYe233** [comment]
But how do i configure rewrite rules in nginx？Results of automatic conversion on internet doesn't work well

**Comment by sinkcup** [comment]
https://laravel.com/docs/6.x/deployment#nginx
