### ISSUE TITLE
Facebook Check in option

### ISSUE THREAD

**Issue by MenaBassily** [wifidog/wifidog-auth-laravel#5]
Any chance it can handle Facebook check in like this video:
https://www.youtube.com/watch?v=XWXgT6ee_jg 

Thanks a lot for your work

**Comment by sinkcup** [comment]
I have watch that video, so, is there any problem?

**Comment by MenaBassily** [comment]
:) I want to be able to develop a similar solution to the one in the video . Do you have a template HTML, css, PHP or Javascript that does that? I don't want to start from scratch

**Comment by sinkcup** [comment]
just read it.

https://github.com/wifidog/wifidog-auth-laravel/blob/master/README.md
