### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by makavel123** [wifidog/wifidog-auth-laravel#57]
hello .thank you for this amazing project. I got everything up and running with docker containers. But what IP do i have to use to connect my openWRT router to the docker container that runs in bridge network mode. somehow i cant manage to build a connection from router to the Auth Server. thank you for your help

**Comment by sinkcup** [comment]
just use `-p` to bind port.

```
docker run -p 8000:80 -e "APP_ENV=local" -e "DB_CONNECTION=sqlite" \
  -e "APP_KEY=base64:L+3avOYCfuq8nnDpHs74+5Et3sx27TssucHQIyqfpDY=" \
  wifidog/wifidog-auth-laravel

open http://127.0.0.1:8000
```
