### ISSUE TITLE
Android 10 - Hamburger Menu

### ISSUE THREAD

**Issue by xraive** [wifidog/wifidog-auth-laravel#72]
Hi there I just wanted to mention that when I connect to my hotspot running "wifidog-auth-laravel" in Android.  I'm unable to  use the hamburger menu to logout.  I can open a browser and switch to "Desktop Mode" to see the menu properly but when it's under mobile view I see the hamburger menu but when I press on it nothing happens.  This is even more of a problem when connecting to the hotspot and Android default browser for signing into Captive Portal pops up.  The default Android browser doesn't give you the option to switch to Desktop Mode.  I don't have this issue on iPhone or iPad.

I'm running Android 10, Samsung OneUI 2.5.

Thanks for the great work.

**Comment by sinkcup** [comment]
could you take some screenshots about this problem?

As a temporary solution, you could change the code to add a logout button in the content area.

![image](https://user-images.githubusercontent.com/4971414/115981731-919d9d00-a5c8-11eb-909b-5ef96331c621.png)

**Comment by sinkcup** [comment]
I'm trying to add logout button in this page.

<img width="427" alt="image" src="https://github.com/user-attachments/assets/3f9756b3-917a-4202-8c34-4b1b1faf8598">
